if(EXISTS "/15-445/bustub-master/build-release/test/binder_test[1]_tests.cmake")
  include("/15-445/bustub-master/build-release/test/binder_test[1]_tests.cmake")
else()
  add_test(binder_test_NOT_BUILT binder_test_NOT_BUILT)
endif()
