if(EXISTS "/15-445/bustub-master/build-release/test/disk_manager_test[1]_tests.cmake")
  include("/15-445/bustub-master/build-release/test/disk_manager_test[1]_tests.cmake")
else()
  add_test(disk_manager_test_NOT_BUILT disk_manager_test_NOT_BUILT)
endif()
