if(EXISTS "/15-445/bustub-master/build-release/test/rwlatch_test[1]_tests.cmake")
  include("/15-445/bustub-master/build-release/test/rwlatch_test[1]_tests.cmake")
else()
  add_test(rwlatch_test_NOT_BUILT rwlatch_test_NOT_BUILT)
endif()
