if(EXISTS "/15-445/bustub-master/build-release/test/tmp_tuple_page_test[1]_tests.cmake")
  include("/15-445/bustub-master/build-release/test/tmp_tuple_page_test[1]_tests.cmake")
else()
  add_test(tmp_tuple_page_test_NOT_BUILT tmp_tuple_page_test_NOT_BUILT)
endif()
