if(EXISTS "/15-445/bustub-master/build-release/test/transaction_test[1]_tests.cmake")
  include("/15-445/bustub-master/build-release/test/transaction_test[1]_tests.cmake")
else()
  add_test(transaction_test_NOT_BUILT transaction_test_NOT_BUILT)
endif()
