if(EXISTS "/15-445/bustub-master/build-release/test/type_test[1]_tests.cmake")
  include("/15-445/bustub-master/build-release/test/type_test[1]_tests.cmake")
else()
  add_test(type_test_NOT_BUILT type_test_NOT_BUILT)
endif()
